#VideoURL: "E:\\Project\\Fire\\FireDet\\Data\\Video\\C0201-1.mp4"
#VideoURL: "E:\\Project\\CNOOC\\EP\\Data\\Video\\field7.mp4"
VideoURL: "rtsp://admin:hebtu123@192.168.1.64:554/Streaming/Channels/101?transportmode=unicast&profile=Profile_1"


MainUi:
  Height: 1200
  Width: 720

RGBCam:
  UserName: admin
  Password: hebtu123
  NeedPrintDebugInfo: true
  PreviewDetectedImg: true
  NeedSaveOriImg: true

ThermalCam:
  OpenOnInit: false
  Width: 160
  Height: 120
  FPS: 9

VisionMea:
  DetModelName: v11s_d01_e300_im640_seg.onnx
  DetBackend: ORT
  RectConfidenceThreshold: 0.88
  IouThreshold: 0.55

